### ISSUE TITLE
Project co-ownership?

### ISSUE THREAD

**Issue by mkhq** [finagle/finagle-websocket#6]
Hi,

we are using finagle-websocket actively and would like to know if its possible to discuss some form of co-ownership? I don't expect that we will do any major changes but we are adding smaller things as needed though. For example, we added the ability of the client to send WS pings in a recent branch:

https://github.com/mkhq/finagle-websocket/compare/master...mkhq:ping-api

As the next thing we are looking at how to enable secure WS connections. For this I'd also like to transition to use a stacked client/server like in finagle-httpx.

https://github.com/twitter/finagle/blob/develop/finagle-httpx/src/main/scala/com/twitter/finagle/Httpx.scala#L111

Please let us know what you think on co-ownership.

Cheers,
Mikael

**Comment by travisbrown** [comment]
@mkhq This sounds good to me—are you comfortable with an informal rule that any pull requests need a +1 from Twitter and your organization before merging?

**Comment by mkhq** [comment]
@travisbrown ok, thats great!
